name = "StaticFFTs"
uuid = "0dbde15c-b3cb-4ddc-be65-d270f8457013"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FFTW = "1"
Primes = "0.4"
StaticArrays = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[targets]
test = ["Test", "FFTW"]
